services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: occupi-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      INFLUXDB_URL: http://influxdb:8181
    depends_on:
      influxdb:
        condition: service_healthy
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   container_name: occupi-frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

  influxdb:
    image: influxdb:3-core
    container_name: occupi-influxdb3
    ports:
      - "8181:8181"
    volumes:
      - influxdb3-data:/var/lib/influxdb3
    environment:
      - INFLUXDB3_HOST_ID=occupi-prod
    command: serve --host-id occupi-prod --http-bind 0.0.0.0:8181 --object-store file --data-dir /var/lib/influxdb3 --without-auth
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  influxdb3-data:
