server:
  port: 8080

spring:
  application:
    name: occupi
  profiles:
    active: dev

influxdb:
  url: http://localhost:8181
  database: occupi
  token: ""

logging:
  level:
    com.occupi: DEBUG
